#include "CharacterClass.h"
#include <algorithm>
#include <sstream>

namespace RPG {

// Static member initialization
std::map<CharacterClass::Class, CharacterClass::ClassDefinition> CharacterClass::s_classDefinitions;
std::map<CharacterClass::Specialization, CharacterClass::SpecializationDefinition> CharacterClass::s_specDefinitions;
bool CharacterClass::s_initialized = false;

CharacterClass::CharacterClass()
    : m_currentClass(Class::NONE)
    , m_currentSpec(Specialization::NONE)
    , m_currentResource(0.0f)
    , m_allowMultiClass(false)
    , m_isPrestigeClass(false)
{
    if (!s_initialized) {
        initializeClassData();
    }
}

CharacterClass::~CharacterClass() {
}

void CharacterClass::initializeClassData() {
    if (s_initialized) return;

    // WARRIOR Class
    ClassDefinition warrior;
    warrior.classType = Class::WARRIOR;
    warrior.name = "Warrior";
    warrior.description = "Master of melee combat, excelling in physical strength and durability";
    warrior.lore = "Warriors are fearless combatants who stand at the front lines of battle.";
    warrior.startingStatBonuses = {
        {CharacterStats::PrimaryStat::STRENGTH, 5},
        {CharacterStats::PrimaryStat::VITALITY, 5},
        {CharacterStats::PrimaryStat::ENDURANCE, 5}
    };
    warrior.startingSkills = {"basic_slash", "defensive_stance"};
    warrior.startingEquipment = {"iron_sword", "leather_armor", "wooden_shield"};
    warrior.classPassives = {
        {"melee_damage", 0.10f},
        {"armor_bonus", 0.15f}
    };
    warrior.skillTrees = {"Warrior_Offense", "Warrior_Defense"};
    warrior.availableSpecs = {Specialization::BERSERKER, Specialization::GUARDIAN};
    warrior.resourceType = "Rage";
    warrior.resourceMax = 100.0f;
    warrior.resourceRegen = 0.0f; // Generated by attacking
    warrior.playstyleTags = {"Melee", "Tank", "DPS"};
    s_classDefinitions[Class::WARRIOR] = warrior;

    // MAGE Class
    ClassDefinition mage;
    mage.classType = Class::MAGE;
    mage.name = "Mage";
    mage.description = "Wielder of arcane magic, devastating enemies from afar";
    mage.lore = "Mages have dedicated their lives to mastering the arcane arts.";
    mage.startingStatBonuses = {
        {CharacterStats::PrimaryStat::INTELLIGENCE, 8},
        {CharacterStats::PrimaryStat::DEXTERITY, 3}
    };
    mage.startingSkills = {"fireball", "frost_armor"};
    mage.startingEquipment = {"apprentice_staff", "cloth_robe"};
    mage.classPassives = {
        {"magic_damage", 0.20f},
        {"mana_cost_reduction", 0.10f},
        {"spell_crit", 0.05f}
    };
    mage.skillTrees = {"Mage_Fire", "Mage_Ice"};
    mage.availableSpecs = {Specialization::PYROMANCER, Specialization::CRYOMANCER};
    mage.resourceType = "Mana";
    mage.resourceMax = 200.0f;
    mage.resourceRegen = 5.0f;
    mage.playstyleTags = {"Ranged", "DPS", "Burst"};
    s_classDefinitions[Class::MAGE] = mage;

    // RANGER Class
    ClassDefinition ranger;
    ranger.classType = Class::RANGER;
    ranger.name = "Ranger";
    ranger.description = "Expert archer and nature guardian, striking from the shadows";
    ranger.lore = "Rangers are skilled hunters who have mastered both bow and beast.";
    ranger.startingStatBonuses = {
        {CharacterStats::PrimaryStat::DEXTERITY, 8},
        {CharacterStats::PrimaryStat::LUCK, 3}
    };
    ranger.startingSkills = {"aimed_shot", "summon_companion"};
    ranger.startingEquipment = {"hunting_bow", "leather_tunic", "quiver"};
    ranger.classPassives = {
        {"ranged_damage", 0.15f},
        {"attack_speed", 0.10f},
        {"dodge_chance", 0.05f}
    };
    ranger.skillTrees = {"Ranger_Archery", "Ranger_Nature"};
    ranger.availableSpecs = {Specialization::MARKSMAN, Specialization::BEASTMASTER};
    ranger.resourceType = "Focus";
    ranger.resourceMax = 100.0f;
    ranger.resourceRegen = 10.0f;
    ranger.playstyleTags = {"Ranged", "DPS", "Pet"};
    s_classDefinitions[Class::RANGER] = ranger;

    // ROGUE Class
    ClassDefinition rogue;
    rogue.classType = Class::ROGUE;
    rogue.name = "Rogue";
    rogue.description = "Master of stealth and deception, eliminating foes with precision";
    rogue.lore = "Rogues strike from the shadows, vanishing before their enemies realize the threat.";
    rogue.startingStatBonuses = {
        {CharacterStats::PrimaryStat::DEXTERITY, 6},
        {CharacterStats::PrimaryStat::LUCK, 6}
    };
    rogue.startingSkills = {"backstab", "stealth", "poison_blade"};
    rogue.startingEquipment = {"steel_dagger", "shadow_cloak"};
    rogue.classPassives = {
        {"crit_chance", 0.15f},
        {"crit_damage", 0.25f},
        {"movement_speed", 0.10f}
    };
    rogue.skillTrees = {"Rogue_Assassination", "Rogue_Shadow"};
    rogue.availableSpecs = {Specialization::ASSASSIN, Specialization::SHADOWDANCER};
    rogue.resourceType = "Energy";
    rogue.resourceMax = 100.0f;
    rogue.resourceRegen = 20.0f;
    rogue.playstyleTags = {"Melee", "DPS", "Burst", "Stealth"};
    s_classDefinitions[Class::ROGUE] = rogue;

    // PALADIN Class
    ClassDefinition paladin;
    paladin.classType = Class::PALADIN;
    paladin.name = "Paladin";
    paladin.description = "Holy warrior combining martial prowess with divine magic";
    paladin.lore = "Paladins are champions of justice, wielding holy light against darkness.";
    paladin.startingStatBonuses = {
        {CharacterStats::PrimaryStat::STRENGTH, 4},
        {CharacterStats::PrimaryStat::INTELLIGENCE, 4},
        {CharacterStats::PrimaryStat::VITALITY, 4}
    };
    paladin.startingSkills = {"holy_strike", "lay_on_hands", "divine_shield"};
    paladin.startingEquipment = {"blessed_mace", "plate_armor", "holy_shield"};
    paladin.classPassives = {
        {"holy_damage", 0.15f},
        {"healing_power", 0.20f},
        {"damage_reduction", 0.10f}
    };
    paladin.skillTrees = {"Paladin_Holy", "Paladin_Protection"};
    paladin.availableSpecs = {Specialization::CRUSADER, Specialization::PROTECTOR};
    paladin.resourceType = "Holy Power";
    paladin.resourceMax = 5.0f;
    paladin.resourceRegen = 0.0f; // Generated by abilities
    paladin.playstyleTags = {"Melee", "Tank", "Support", "Healer"};
    s_classDefinitions[Class::PALADIN] = paladin;

    // Initialize Specializations

    // Berserker (Warrior)
    SpecializationDefinition berserker;
    berserker.specType = Specialization::BERSERKER;
    berserker.parentClass = Class::WARRIOR;
    berserker.name = "Berserker";
    berserker.description = "Unleash primal fury for devastating damage";
    berserker.levelRequirement = 20;
    berserker.statBonuses = {
        {CharacterStats::PrimaryStat::STRENGTH, 10},
        {CharacterStats::PrimaryStat::VITALITY, -5}
    };
    berserker.specPassives = {
        {"damage_while_low_health", 0.50f},
        {"attack_speed", 0.20f}
    };
    berserker.uniqueAbilities = {"whirlwind", "bloodlust", "reckless_abandon"};
    berserker.ultimateAbility = "titans_wrath";
    berserker.skillTreeBonuses = {{"Warrior_Offense", 0.25f}};
    s_specDefinitions[Specialization::BERSERKER] = berserker;

    // Guardian (Warrior)
    SpecializationDefinition guardian;
    guardian.specType = Specialization::GUARDIAN;
    guardian.parentClass = Class::WARRIOR;
    guardian.name = "Guardian";
    guardian.description = "Become an unbreakable shield for your allies";
    guardian.levelRequirement = 20;
    guardian.statBonuses = {
        {CharacterStats::PrimaryStat::ENDURANCE, 10},
        {CharacterStats::PrimaryStat::VITALITY, 10}
    };
    guardian.specPassives = {
        {"damage_reduction", 0.25f},
        {"threat_generation", 1.00f},
        {"block_chance", 0.15f}
    };
    guardian.uniqueAbilities = {"shield_wall", "taunt", "intervene"};
    guardian.ultimateAbility = "last_stand";
    guardian.skillTreeBonuses = {{"Warrior_Defense", 0.30f}};
    s_specDefinitions[Specialization::GUARDIAN] = guardian;

    // Pyromancer (Mage)
    SpecializationDefinition pyromancer;
    pyromancer.specType = Specialization::PYROMANCER;
    pyromancer.parentClass = Class::MAGE;
    pyromancer.name = "Pyromancer";
    pyromancer.description = "Master of destructive flame magic";
    pyromancer.levelRequirement = 20;
    pyromancer.statBonuses = {
        {CharacterStats::PrimaryStat::INTELLIGENCE, 15}
    };
    pyromancer.specPassives = {
        {"fire_damage", 0.40f},
        {"burn_damage_over_time", 0.20f}
    };
    pyromancer.uniqueAbilities = {"flame_strike", "combustion", "meteor"};
    pyromancer.ultimateAbility = "inferno";
    pyromancer.skillTreeBonuses = {{"Mage_Fire", 0.35f}};
    s_specDefinitions[Specialization::PYROMANCER] = pyromancer;

    // Cryomancer (Mage)
    SpecializationDefinition cryomancer;
    cryomancer.specType = Specialization::CRYOMANCER;
    cryomancer.parentClass = Class::MAGE;
    cryomancer.name = "Cryomancer";
    cryomancer.description = "Control the battlefield with freezing magic";
    cryomancer.levelRequirement = 20;
    cryomancer.statBonuses = {
        {CharacterStats::PrimaryStat::INTELLIGENCE, 12},
        {CharacterStats::PrimaryStat::VITALITY, 5}
    };
    cryomancer.specPassives = {
        {"frost_damage", 0.35f},
        {"slow_effectiveness", 0.30f},
        {"freeze_duration", 0.25f}
    };
    cryomancer.uniqueAbilities = {"ice_lance", "frost_nova", "blizzard"};
    cryomancer.ultimateAbility = "absolute_zero";
    cryomancer.skillTreeBonuses = {{"Mage_Ice", 0.35f}};
    s_specDefinitions[Specialization::CRYOMANCER] = cryomancer;

    // Marksman (Ranger)
    SpecializationDefinition marksman;
    marksman.specType = Specialization::MARKSMAN;
    marksman.parentClass = Class::RANGER;
    marksman.name = "Marksman";
    marksman.description = "Precision archer dealing devastating single-target damage";
    marksman.levelRequirement = 20;
    marksman.statBonuses = {
        {CharacterStats::PrimaryStat::DEXTERITY, 15}
    };
    marksman.specPassives = {
        {"headshot_damage", 1.00f},
        {"crit_chance", 0.20f},
        {"attack_range", 0.30f}
    };
    marksman.uniqueAbilities = {"sniper_shot", "volley", "piercing_arrow"};
    marksman.ultimateAbility = "deadeye";
    marksman.skillTreeBonuses = {{"Ranger_Archery", 0.40f}};
    s_specDefinitions[Specialization::MARKSMAN] = marksman;

    // Beastmaster (Ranger)
    SpecializationDefinition beastmaster;
    beastmaster.specType = Specialization::BEASTMASTER;
    beastmaster.parentClass = Class::RANGER;
    beastmaster.name = "Beastmaster";
    beastmaster.description = "Command powerful beasts to fight alongside you";
    beastmaster.levelRequirement = 20;
    beastmaster.statBonuses = {
        {CharacterStats::PrimaryStat::DEXTERITY, 8},
        {CharacterStats::PrimaryStat::INTELLIGENCE, 8}
    };
    beastmaster.specPassives = {
        {"pet_damage", 0.60f},
        {"pet_health", 0.50f},
        {"number_of_pets", 1.0f}
    };
    beastmaster.uniqueAbilities = {"call_of_the_wild", "bestial_wrath", "mend_pet"};
    beastmaster.ultimateAbility = "stampede";
    beastmaster.skillTreeBonuses = {{"Ranger_Nature", 0.40f}};
    s_specDefinitions[Specialization::BEASTMASTER] = beastmaster;

    // Assassin (Rogue)
    SpecializationDefinition assassin;
    assassin.specType = Specialization::ASSASSIN;
    assassin.parentClass = Class::ROGUE;
    assassin.name = "Assassin";
    assassin.description = "Master of lethal strikes and execution";
    assassin.levelRequirement = 20;
    assassin.statBonuses = {
        {CharacterStats::PrimaryStat::DEXTERITY, 12},
        {CharacterStats::PrimaryStat::LUCK, 8}
    };
    assassin.specPassives = {
        {"backstab_damage", 1.00f},
        {"execute_threshold", 0.15f},
        {"poison_damage", 0.40f}
    };
    assassin.uniqueAbilities = {"eviscerate", "vendetta", "marked_for_death"};
    assassin.ultimateAbility = "death_from_above";
    assassin.skillTreeBonuses = {{"Rogue_Assassination", 0.45f}};
    s_specDefinitions[Specialization::ASSASSIN] = assassin;

    // Shadowdancer (Rogue)
    SpecializationDefinition shadowdancer;
    shadowdancer.specType = Specialization::SHADOWDANCER;
    shadowdancer.parentClass = Class::ROGUE;
    shadowdancer.name = "Shadowdancer";
    shadowdancer.description = "Blend into shadows for unmatched mobility and evasion";
    shadowdancer.levelRequirement = 20;
    shadowdancer.statBonuses = {
        {CharacterStats::PrimaryStat::DEXTERITY, 15},
        {CharacterStats::PrimaryStat::ENDURANCE, 5}
    };
    shadowdancer.specPassives = {
        {"dodge_chance", 0.25f},
        {"movement_speed", 0.30f},
        {"stealth_effectiveness", 0.50f}
    };
    shadowdancer.uniqueAbilities = {"shadow_step", "vanish", "smoke_bomb"};
    shadowdancer.ultimateAbility = "shadow_dance";
    shadowdancer.skillTreeBonuses = {{"Rogue_Shadow", 0.40f}};
    s_specDefinitions[Specialization::SHADOWDANCER] = shadowdancer;

    // Crusader (Paladin)
    SpecializationDefinition crusader;
    crusader.specType = Specialization::CRUSADER;
    crusader.parentClass = Class::PALADIN;
    crusader.name = "Crusader";
    crusader.description = "Righteous warrior dealing holy damage to evil";
    crusader.levelRequirement = 20;
    crusader.statBonuses = {
        {CharacterStats::PrimaryStat::STRENGTH, 10},
        {CharacterStats::PrimaryStat::INTELLIGENCE, 8}
    };
    crusader.specPassives = {
        {"holy_damage", 0.35f},
        {"damage_vs_undead", 0.50f},
        {"healing_on_crit", 0.20f}
    };
    crusader.uniqueAbilities = {"holy_wrath", "consecration", "judgment"};
    crusader.ultimateAbility = "divine_storm";
    crusader.skillTreeBonuses = {{"Paladin_Holy", 0.40f}};
    s_specDefinitions[Specialization::CRUSADER] = crusader;

    // Protector (Paladin)
    SpecializationDefinition protector;
    protector.specType = Specialization::PROTECTOR;
    protector.parentClass = Class::PALADIN;
    protector.name = "Protector";
    protector.description = "Guardian who shields allies with divine power";
    protector.levelRequirement = 20;
    protector.statBonuses = {
        {CharacterStats::PrimaryStat::VITALITY, 12},
        {CharacterStats::PrimaryStat::INTELLIGENCE, 6}
    };
    protector.specPassives = {
        {"damage_reduction", 0.20f},
        {"ally_healing", 0.30f},
        {"threat_generation", 0.80f}
    };
    protector.uniqueAbilities = {"blessing_of_protection", "hand_of_sacrifice", "divine_guardian"};
    protector.ultimateAbility = "avenging_shield";
    protector.skillTreeBonuses = {{"Paladin_Protection", 0.35f}};
    s_specDefinitions[Specialization::PROTECTOR] = protector;

    s_initialized = true;
}

void CharacterClass::setClass(Class classType) {
    if (m_currentClass != Class::NONE) {
        removeClassBonuses();
    }

    m_currentClass = classType;

    if (m_currentClass != Class::NONE) {
        applyClassBonuses();
        const ClassDefinition* classDef = getClassDefinition();
        if (classDef) {
            m_currentResource = classDef->resourceMax;
        }
    }
}

const CharacterClass::ClassDefinition* CharacterClass::getClassDefinition() const {
    auto it = s_classDefinitions.find(m_currentClass);
    return (it != s_classDefinitions.end()) ? &it->second : nullptr;
}

bool CharacterClass::canChangeClass() const {
    // Can change class if no class selected or multi-classing is enabled
    return m_currentClass == Class::NONE || m_allowMultiClass;
}

bool CharacterClass::setSpecialization(Specialization spec) {
    if (!canSpecialize()) {
        return false;
    }

    // Verify spec matches current class
    auto it = s_specDefinitions.find(spec);
    if (it == s_specDefinitions.end() || it->second.parentClass != m_currentClass) {
        return false;
    }

    if (m_currentSpec != Specialization::NONE) {
        removeSpecBonuses();
    }

    m_currentSpec = spec;
    applySpecBonuses();
    return true;
}

const CharacterClass::SpecializationDefinition* CharacterClass::getSpecDefinition() const {
    auto it = s_specDefinitions.find(m_currentSpec);
    return (it != s_specDefinitions.end()) ? &it->second : nullptr;
}

bool CharacterClass::canSpecialize() const {
    // Must have a class to specialize
    return m_currentClass != Class::NONE;
}

std::vector<CharacterClass::Specialization> CharacterClass::getAvailableSpecializations() const {
    const ClassDefinition* classDef = getClassDefinition();
    if (!classDef) {
        return {};
    }
    return classDef->availableSpecs;
}

std::string CharacterClass::getClassName(Class classType) {
    auto it = s_classDefinitions.find(classType);
    return (it != s_classDefinitions.end()) ? it->second.name : "Unknown";
}

std::string CharacterClass::getSpecializationName(Specialization spec) {
    auto it = s_specDefinitions.find(spec);
    return (it != s_specDefinitions.end()) ? it->second.name : "None";
}

std::string CharacterClass::getClassDescription(Class classType) {
    auto it = s_classDefinitions.find(classType);
    return (it != s_classDefinitions.end()) ? it->second.description : "";
}

std::vector<CharacterClass::Class> CharacterClass::getAllClasses() {
    return {Class::WARRIOR, Class::MAGE, Class::RANGER, Class::ROGUE, Class::PALADIN};
}

std::map<CharacterStats::PrimaryStat, int> CharacterClass::getTotalStatBonuses() const {
    std::map<CharacterStats::PrimaryStat, int> bonuses;

    const ClassDefinition* classDef = getClassDefinition();
    if (classDef) {
        bonuses = classDef->startingStatBonuses;
    }

    const SpecializationDefinition* specDef = getSpecDefinition();
    if (specDef) {
        for (const auto& bonus : specDef->statBonuses) {
            bonuses[bonus.first] += bonus.second;
        }
    }

    return bonuses;
}

std::map<std::string, float> CharacterClass::getTotalPassives() const {
    std::map<std::string, float> passives;

    const ClassDefinition* classDef = getClassDefinition();
    if (classDef) {
        passives = classDef->classPassives;
    }

    const SpecializationDefinition* specDef = getSpecDefinition();
    if (specDef) {
        for (const auto& passive : specDef->specPassives) {
            passives[passive.first] += passive.second;
        }
    }

    return passives;
}

std::vector<std::string> CharacterClass::getUniqueAbilities() const {
    std::vector<std::string> abilities;

    const ClassDefinition* classDef = getClassDefinition();
    if (classDef) {
        abilities = classDef->startingSkills;
    }

    const SpecializationDefinition* specDef = getSpecDefinition();
    if (specDef) {
        abilities.insert(abilities.end(),
                        specDef->uniqueAbilities.begin(),
                        specDef->uniqueAbilities.end());
        if (!specDef->ultimateAbility.empty()) {
            abilities.push_back(specDef->ultimateAbility);
        }
    }

    return abilities;
}

CharacterClass::ResourceInfo CharacterClass::getResourceInfo() const {
    ResourceInfo info = {"None", 0.0f, 0.0f, 0.0f};

    const ClassDefinition* classDef = getClassDefinition();
    if (classDef) {
        info.type = classDef->resourceType;
        info.current = m_currentResource;
        info.maximum = classDef->resourceMax;
        info.regen = classDef->resourceRegen;
    }

    return info;
}

void CharacterClass::modifyResource(float amount) {
    const ClassDefinition* classDef = getClassDefinition();
    if (!classDef) return;

    m_currentResource += amount;
    m_currentResource = std::max(0.0f, std::min(m_currentResource, classDef->resourceMax));
}

void CharacterClass::setResource(float amount) {
    const ClassDefinition* classDef = getClassDefinition();
    if (!classDef) return;

    m_currentResource = std::max(0.0f, std::min(amount, classDef->resourceMax));
}

bool CharacterClass::hasClassMechanic(const std::string& mechanic) const {
    const auto passives = getTotalPassives();
    return passives.find(mechanic) != passives.end();
}

float CharacterClass::getClassMechanicValue(const std::string& mechanic) const {
    const auto passives = getTotalPassives();
    auto it = passives.find(mechanic);
    return (it != passives.end()) ? it->second : 0.0f;
}

bool CharacterClass::addSecondaryClass(Class classType) {
    if (!m_allowMultiClass || classType == m_currentClass) {
        return false;
    }

    if (std::find(m_secondaryClasses.begin(), m_secondaryClasses.end(), classType)
        != m_secondaryClasses.end()) {
        return false; // Already have this class
    }

    m_secondaryClasses.push_back(classType);
    return true;
}

void CharacterClass::unlockPrestigeClasses() {
    m_isPrestigeClass = true;
}

void CharacterClass::applyClassBonuses() {
    const ClassDefinition* classDef = getClassDefinition();
    if (classDef) {
        m_appliedStatBonuses = classDef->startingStatBonuses;
        m_appliedPassives = classDef->classPassives;
    }
}

void CharacterClass::removeClassBonuses() {
    m_appliedStatBonuses.clear();
    m_appliedPassives.clear();
}

void CharacterClass::applySpecBonuses() {
    const SpecializationDefinition* specDef = getSpecDefinition();
    if (specDef) {
        for (const auto& bonus : specDef->statBonuses) {
            m_appliedStatBonuses[bonus.first] += bonus.second;
        }
        for (const auto& passive : specDef->specPassives) {
            m_appliedPassives[passive.first] += passive.second;
        }
    }
}

void CharacterClass::removeSpecBonuses() {
    // Would need to track what was added by spec separately
    // For now, recalculate from class
    applyClassBonuses();
}

const CharacterClass::ClassDefinition& CharacterClass::getClassData(Class classType) {
    return s_classDefinitions[classType];
}

const CharacterClass::SpecializationDefinition& CharacterClass::getSpecData(Specialization spec) {
    return s_specDefinitions[spec];
}

std::string CharacterClass::serialize() const {
    std::stringstream ss;
    ss << static_cast<int>(m_currentClass) << ","
       << static_cast<int>(m_currentSpec) << ","
       << m_currentResource;
    return ss.str();
}

bool CharacterClass::deserialize(const std::string& data) {
    // Implementation for deserialization
    return true;
}

} // namespace RPG
